allowBuilds:
  '@google/genai': true
  esbuild: true
  protobufjs: true
  sharp: true
  unrs-resolver: true

ignoredBuiltDependencies:
  - unrs-resolver

onlyBuiltDependencies:
  - esbuild
  - "@tailwindcss/oxide"
  - sharp
